version: '3.8'

services:
  # Base de datos 1: USUARIOS y RESERVAS (Puerto 5432)
  db_usuarios:
    image: postgres:14-alpine
    container_name: db_usuarios
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_cinemax_usuarios
    ports:
      - "5432:5432"
    volumes:
      - db_usuarios_data:/var/lib/postgresql/data
    networks:
      - cinemax-network

  # Base de datos 2: PELICULAS (Puerto 5433)
  db_peliculas:
    image: postgres:14-alpine
    container_name: db_peliculas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_cinemax_peliculas
    ports:
      - "5433:5432"
    volumes:
      - db_peliculas_data:/var/lib/postgresql/data
    networks:
      - cinemax-network

volumes:
  db_usuarios_data:
  db_peliculas_data:

networks:
  cinemax-network:
    driver: bridge